# Join our discord for support: https://discord.gg/3mJuxUW
Enabled: false

# Add Prize ID's here, NOT commands
Kill-Prize:
  - ''
Final-Kill-Prize:
  - ''
Bed-Break-Prize:
  - ''
Earn-Achievement-Prize:
  - ''
Join-Arena-Prize:
  - ''
Leave-Arena-Prize:
  - ''
Rejoin-Arena-Prize:
  - ''

End-Game-Prizes:
  Minimum-Time: 2400
  Win-Prizes:
    - ''
  Lose-Prizes:
    - ''

Playtime-Prize:
  Enabled: false
  Interval: 2400
  Prizes:
    - 'Prize-ID-Here'
    - 'Prize-1'

Prizes:
  Prize-1:
    Enabled: true
    Permission: ''
    Commands:
      - ''
    Broadcast:
      - ''
    Player-Message:
      - ''
    Supported-Arenas:
      - ''

  Prize-2:
    Enabled: true
    Permission: ''
    Commands:
      - ''
    Broadcast:
      - ''
    Player-Message:
      - ''
    Supported-Arenas:
      - ''

  Prize-3:
    Enabled: true
    Permission: ''
    Commands:
      - ''
    Broadcast:
      - ''
    Player-Message:
      - ''
    Supported-Arenas:
      - ''