#Use %player% to get the player's name
#Use %victim% to get the victim's name NOTE: This placeholder will not work for events without a victim
#Please Note Commands are run as console, NOT as player
bed-break-prize:
  - 'say %player% Broke a Bed!'
kill-prize:
  - 'say %player% killed %victim% - Standard Kill'
final-kill-prize:
  - 'say %player% killed %victim% - Final Kill'
win-prize:
  - ''
lose-prize:
  - ''

#interval in ticks (20 tics in 1 sec) (2 min = 2400 ticks)
#Placeholders %player%
playtime-prize:
  enabled: false
  interval: 2400
  message:
    - '&6+25 Bed Wars Experience (Time Played)'
    - '&b+15 coins! (Time Played)'
  commands:
    - ''

#Message displayed on round start
#!!!This feature will be removed shortly, as it is built into MBedwars!!!
start-message:
  enabled: false
  message:
    - '&e----------------------------'
    - '&aPrizeCommands for MBedwars'
    - '&bBy: MetallicGoat'
    - '&e----------------------------'