# Join our discord for support: https://discord.gg/3mJuxUW
# Please read the setup instructions here: https://github.com/MetallicGoat/PrizeCommands
# Before asking for help on discord
Enabled: false

# Add Prize ID's here, NOT commands
Kill-Prizes:
  - ''
Final-Kill-Prizes:
  - ''
Bed-Break-Prizes:
  - ''
Earn-Achievement-Prizes:
  - ''
Join-Arena-Prizes:
  - ''
Leave-Arena-Prizes:
  - ''
Rejoin-Arena-Prizes:
  - ''

End-Game-Prizes:
  Minimum-Time: 2400
  Win-Prizes:
    - ''
  Lose-Prizes:
    - ''

Playtime-Prize:
  Enabled: false
  Interval: 2400
  Prizes:
    - ''

Prizes:
  Prize-1:
    Enabled: true
    Permission: ''
    Commands:
      - ''
    Broadcast:
      - ''
    Player-Message:
      - ''
    Supported-Arenas:
      - ''

  Prize-2:
    Enabled: true
    Permission: ''
    Commands:
      - ''
    Broadcast:
      - ''
    Player-Message:
      - ''
    Supported-Arenas:
      - ''

  Prize-3:
    Enabled: true
    Permission: ''
    Commands:
      - ''
    Broadcast:
      - ''
    Player-Message:
      - ''
    Supported-Arenas:
      - ''